# Generated by Django 6.0.2 on 2026-02-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="browser_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
