# Generated by Django 6.0.2 on 2026-02-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_complaint_browser_info_complaint_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image of the issue",
                null=True,
                upload_to="complaints/",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="location",
            field=models.CharField(
                blank=True, help_text="Location of the issue", max_length=255, null=True
            ),
        ),
    ]
